---
output_dir: "."
title: "RNotebookExample"
output: html_document
---
# This is a heading, not a comment



```{r load-data, message = FALSE}
#now you can make comments the way we learned before!
#load libraries
library(tidyverse)
library(kableExtra) #used for kbl() functions
library(rmarkdown) #use for paged_table function
library(ggpubr)

#read file into r
pop_data <- read_csv("data/gapminder_data.csv")

#create a table with data from European countries in 2007 - ordered by life expectancy
euro_data_tbl <- pop_data %>% 
  filter(continent == "Europe" & year == "2007") %>% 
  select(-continent, -year) %>% 
  arrange(desc(lifeExp)) %>% 
  rename(Country = country, "Population Size" = pop, "Life Expectancy" = lifeExp, "GDP"= gdpPercap)

#keep only UK data
uk_data_fig <- pop_data %>% 
  filter(country == "United Kingdom") %>% 
  mutate(year=as_factor(year))
  
```

The results of euro_data_tbl are displayed in the Table below:

```{r kbl}
euro_data_tbl %>% 
  kbl() %>% 
  kable_styling(bootstrap_options = "striped", full_width = F) %>% 
  scroll_box(width = "100%", height =  "200px")
```

This is a better way to display long tables:
```{r paged-table}
paged_table(euro_data_tbl)
```

# Adding Images

```{r}
euro_data_fig <- pop_data %>% 
  filter(continent == "Europe") %>% 
  mutate(year = as_factor(year)) 


euro_plot <- euro_data_fig %>% 
  ggplot(mapping = aes(x = year, y = lifeExp)) +
  geom_violin() +
  stat_summary(fun.y = median, geom = "point")

euro_plot


```
Now we will display more than one image together:

```{r fig-comp}
#UK plot
uk_plot <- uk_data_fig %>% 
  ggplot(mapping = aes(x=year, y = lifeExp)) +
  geom_point()

#plot EU and UK plots together
ggarrange(euro_plot, uk_plot, ncol = 2, nrow = 1, labels = "AUTO")


```

